### ISSUE TITLE
switch from "auto-commit on change" to normal commits

### ISSUE THREAD

**Issue by antonkulaga** [scalation/scalation#13]
With auto-commit on change it is very hard to understand what is happening with the library, it would be better if you would finish migration to git and will make commits with meaningful commit messages instead of auto-ones

**Comment by mvnural** [comment]
The project is currently hosted at http://cobweb.cs.uga.edu/~jam/scalation_1.2/README.html . The github repo is merely a mirror to keep track of changes in a more consistent way. 

The codebase is rapidly changing as we are getting ready for an official release. We still need to complete a few major tasks before this milestone. Some of the main items are making the codebase more stable, modularization and adding scalatests to maintain the integrity of the codebase. We have plans to move development completely to the VCS once as the code becomes more stable. 

Since we are a small academic team consisting of a professor and a few graduate students, other priorities sometimes take over unfortunately. If you would like to help out with some of these tasks such as writing scalatests we would be more than grateful.

Thank you for your patience as we are working hard to make an official release.

**Comment by antonkulaga** [comment]
@mvnural it is normal to use github even with very unstable code. 

The need in differential equations and dynamic simulations is very high as current major scala math libs like Breeze do not support them while java libs like Apache Common Math are very ugly.

> If you would like to help out with some of these tasks 

I already started to help (see my pull request https://github.com/scalation/scalation/pull/12 ) with build configuration
